
import React, { useState, useEffect, useRef } from 'react';
import { Clock, AlertTriangle, ChevronRight, Flag, Calculator, Monitor, Target, BookOpen, ArrowRight, Filter, CheckCircle } from 'lucide-react';

type QuestionType = 'Multiple Choice' | 'Fill-in-the-Blank' | 'Passage-Based';

interface Question {
    id: number;
    text: string;
    options?: string[];
    correct: number | string;
    domain: string;
    difficulty: 'Easy' | 'Medium' | 'Hard';
    type: QuestionType;
    explanation?: string;
    passage?: string;
}

const ALL_TOPICS = [
    "Heart of Algebra",
    "Problem Solving and Data Analysis",
    "Passport to Advanced Math",
    "Geometry and Trigonometry",
    "Information and Ideas",
    "Craft and Structure",
    "Expression of Ideas",
    "Standard English Conventions"
];

const MOCK_QUESTIONS: Question[] = [
    {
        id: 1,
        domain: "Craft and Structure",
        difficulty: "Hard",
        type: "Passage-Based",
        passage: "The following text is adapted from a novel. The protagonist, an aspiring artist, reflects on her early attempts at painting.\n\n'I labored over the canvas, layering pigment upon pigment, hoping to capture the luminescence of the morning light. Yet, with each stroke, the image became muddier, the clarity I sought receding further into a haze of gray.'",
        text: "Based on the text, how does the protagonist feel about her painting progress?",
        options: [
            "She is confident that she will eventually succeed.",
            "She is frustrated by her inability to translate her vision to the canvas.",
            "She is experimenting with a new technique that requires heavy layering.",
            "She prefers abstract representations over realistic ones."
        ],
        correct: 1,
        explanation: "The text describes her 'laboring' and the image becoming 'muddier' as the clarity 'receded', indicating frustration and failure to capture the light."
    },
    {
        id: 2,
        domain: "Heart of Algebra",
        difficulty: "Medium",
        type: "Multiple Choice",
        text: "If 3x + 2y = 14 and 5x - y = 19, what is the value of x + y?",
        options: ["3", "5", "7", "4"],
        correct: 1, 
        explanation: "Multiply the second equation by 2: 10x - 2y = 38. Add to first equation: 13x = 52 -> x = 4. Substitute x into second eq: 20 - y = 19 -> y = 1. x + y = 5."
    },
    {
        id: 99,
        domain: "Heart of Algebra",
        difficulty: "Medium",
        type: "Fill-in-the-Blank",
        text: "If 2(x + 3) = 16, what is the value of x?",
        correct: "5",
        options: [],
        explanation: "Divide by 2: x + 3 = 8. Subtract 3: x = 5."
    }
];

for (let i = 5; i <= 50; i++) {
    const isPassage = i % 5 === 0;
    const isFillIn = i % 7 === 0;
    MOCK_QUESTIONS.push({
        id: i,
        domain: ALL_TOPICS[i % ALL_TOPICS.length],
        difficulty: i % 3 === 0 ? "Hard" : i % 2 === 0 ? "Medium" : "Easy",
        type: isPassage ? "Passage-Based" : isFillIn ? "Fill-in-the-Blank" : "Multiple Choice",
        passage: isPassage ? "This is a simulated reading passage generated by the AI Core to test comprehension skills in a high-stakes environment..." : undefined,
        text: `Simulated Question #${i}: AI Generated content placeholder for ${ALL_TOPICS[i % ALL_TOPICS.length]}. Solve for X if f(x) = ...`,
        options: isFillIn ? [] : ["Option A", "Option B", "Option C", "Option D"],
        correct: isFillIn ? "42" : 0,
        explanation: "This is an AI generated explanation. In a real scenario, the Gemini API would populate this."
    });
}

const ExamSimulator: React.FC = () => {
    const [mode, setMode] = useState<'intro' | 'instructions' | 'exam' | 'practice-setup' | 'practice' | 'results'>('intro');
    const [questions, setQuestions] = useState<Question[]>([]);
    const [currentQIndex, setCurrentQIndex] = useState(0);
    const [answers, setAnswers] = useState<Record<number, string | number>>({});
    const [flags, setFlags] = useState<number[]>([]);
    const [timeLeft, setTimeLeft] = useState(0);
    const [isPaused, setIsPaused] = useState(false);
    const [showExitWarning, setShowExitWarning] = useState(false);
    
    // Ref to track interval for cleanup
    const timerRef = useRef<NodeJS.Timeout | null>(null);

    // Timer & Security
    useEffect(() => {
        if ((mode === 'exam' || mode === 'practice') && timeLeft > 0 && !isPaused) {
            timerRef.current = setInterval(() => setTimeLeft(p => p - 1), 1000);
        } else if (timeLeft === 0 && (mode === 'exam' || mode === 'practice')) {
            finishExam();
        }
        
        return () => {
            if (timerRef.current) clearInterval(timerRef.current);
        };
    }, [timeLeft, mode, isPaused]);

    useEffect(() => {
        if (mode === 'exam') {
            const handleVisibilityChange = () => { 
                if (document.hidden) setShowExitWarning(true); 
            };
            // Only prevent copy in Exam mode to allow note-taking in Practice
            const preventCopy = (e: Event) => {
                if(mode === 'exam') e.preventDefault();
            };
            
            document.addEventListener('visibilitychange', handleVisibilityChange);
            document.addEventListener('contextmenu', preventCopy);
            document.addEventListener('copy', preventCopy);
            
            // Try fullscreen but handle failure gracefully
            if (document.documentElement.requestFullscreen) {
                document.documentElement.requestFullscreen().catch(err => console.log("Fullscreen denied:", err));
            }

            return () => {
                document.removeEventListener('visibilitychange', handleVisibilityChange);
                document.removeEventListener('contextmenu', preventCopy);
                document.removeEventListener('copy', preventCopy);
                if (document.exitFullscreen && document.fullscreenElement) {
                    document.exitFullscreen().catch(() => {});
                }
            };
        }
    }, [mode]);

    const startExam = () => {
        setQuestions(MOCK_QUESTIONS);
        setTimeLeft(64 * 60); 
        setMode('exam');
        setCurrentQIndex(0);
        setAnswers({});
        setFlags([]);
        setIsPaused(false);
        setShowExitWarning(false);
    };

    const finishExam = () => {
        setMode('results');
        if (document.fullscreenElement) document.exitFullscreen().catch(() => {});
    };

    const handleAnswer = (value: string | number) => {
        if (!questions[currentQIndex]) return;
        setAnswers(prev => ({ ...prev, [questions[currentQIndex].id]: value }));
    };

    const formatTime = (seconds: number) => {
        const m = Math.floor(seconds / 60);
        const s = seconds % 60;
        return `${m}:${s.toString().padStart(2, '0')}`;
    };

    const score = Object.keys(answers).reduce((acc, qId) => {
        const q = questions.find(q => q.id === Number(qId));
        if (!q) return acc;
        const ans = answers[Number(qId)];
        if (q.type === 'Fill-in-the-Blank') {
            if (String(ans).trim() === String(q.correct)) return acc + 1;
        } else {
            if (ans === q.correct) return acc + 1;
        }
        return acc;
    }, 0);

    // INTRO MODE
    if (mode === 'intro') {
        return (
            <div className="min-h-screen bg-black pt-24 px-4 pb-12 flex items-center justify-center relative">
                <div className="absolute inset-0 grid-bg opacity-10"></div>
                <div className="max-w-6xl w-full grid grid-cols-1 md:grid-cols-2 gap-8 relative z-10">
                    <div className="group relative bg-void-lighter border border-white/10 rounded-[40px] p-12 overflow-hidden hover:border-cyber/50 transition-all duration-500 cursor-pointer" onClick={() => setMode('instructions')}>
                        <div className="absolute inset-0 bg-gradient-to-br from-cyber/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity"></div>
                        <div className="relative z-10">
                            <div className="w-24 h-24 bg-black border-2 border-white/10 rounded-3xl flex items-center justify-center text-white mb-8 shadow-2xl group-hover:scale-110 transition-transform group-hover:border-cyber">
                                <Monitor size={48} className="text-gray-300 group-hover:text-cyber transition-colors" />
                            </div>
                            <h2 className="text-5xl font-black text-white mb-4 tracking-tight">FULL EXAM</h2>
                            <p className="text-gray-400 mb-10 text-xl leading-relaxed">
                                To'liq imtihon simulyatsiyasi. 64 daqiqa. Tanaffuslar. Qattiq rejim. O'z bilimingizni haqiqiy sinovdan o'tkazing.
                            </p>
                            <button className="w-full bg-white text-black py-5 rounded-2xl font-black text-xl hover:bg-cyber transition-all flex items-center justify-center gap-3 shadow-lg group-hover:shadow-[0_0_30px_rgba(0,240,255,0.4)]">
                                BOSHLASH <ArrowRight size={24} />
                            </button>
                        </div>
                    </div>

                    <div className="group relative bg-void-lighter border border-white/10 rounded-[40px] p-12 overflow-hidden hover:border-purple-500/50 transition-all duration-500 cursor-pointer" onClick={() => startExam()}>
                        <div className="absolute inset-0 bg-gradient-to-br from-purple-500/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity"></div>
                        <div className="relative z-10">
                            <div className="w-24 h-24 bg-black border-2 border-white/10 rounded-3xl flex items-center justify-center text-white mb-8 shadow-2xl group-hover:scale-110 transition-transform group-hover:border-purple-500">
                                <Target size={48} className="text-gray-300 group-hover:text-purple-500 transition-colors" />
                            </div>
                            <h2 className="text-5xl font-black text-white mb-4 tracking-tight">PRACTICE</h2>
                            <p className="text-gray-400 mb-10 text-xl leading-relaxed">
                                Erkin rejim. Mavzular bo'yicha mashq qiling. Vaqt chegaralanmagan. Xatolarni darhol ko'ring.
                            </p>
                            <button className="w-full bg-purple-600 text-white py-5 rounded-2xl font-black text-xl hover:bg-purple-500 transition-all flex items-center justify-center gap-3 shadow-lg">
                                MASHQ QILISH <Filter size={24} />
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        );
    }

    if (mode === 'instructions') {
        return (
            <div className="min-h-screen bg-black flex items-center justify-center p-4 relative">
                <div className="absolute inset-0 bg-red-500/5 animate-pulse pointer-events-none"></div>
                <div className="bg-void-lighter border border-red-500/30 p-12 rounded-[40px] max-w-3xl w-full shadow-2xl relative overflow-hidden">
                    <div className="absolute top-0 left-0 w-full h-2 bg-gradient-to-r from-red-600 via-orange-600 to-red-600"></div>
                    <h2 className="text-5xl font-black text-white mb-8 flex items-center gap-4">
                        <AlertTriangle className="text-red-500" size={48} /> 
                        QOIDALAR
                    </h2>
                    
                    <div className="space-y-6 text-gray-300 mb-12 text-lg">
                        <div className="flex gap-6 items-center p-4 bg-white/5 rounded-2xl border border-white/5">
                            <div className="min-w-[40px] h-10 rounded-full bg-red-500/20 text-red-500 flex items-center justify-center font-black text-xl border border-red-500/50">1</div>
                            <p>To'liq ekran rejimi majburiy. Chiqib ketish imtihonni to'xtatadi.</p>
                        </div>
                        <div className="flex gap-6 items-center p-4 bg-white/5 rounded-2xl border border-white/5">
                            <div className="min-w-[40px] h-10 rounded-full bg-red-500/20 text-red-500 flex items-center justify-center font-black text-xl border border-red-500/50">2</div>
                            <p>Kopiya qilish, skrinshot olish yoki boshqa ilovalarni ochish taqiqlanadi (AI Proctoring).</p>
                        </div>
                        <div className="flex gap-6 items-center p-4 bg-white/5 rounded-2xl border border-white/5">
                            <div className="min-w-[40px] h-10 rounded-full bg-red-500/20 text-red-500 flex items-center justify-center font-black text-xl border border-red-500/50">3</div>
                            <p>Vaqt tugashi bilan javoblar avtomatik yuboriladi.</p>
                        </div>
                    </div>

                    <div className="flex gap-6">
                        <button onClick={() => setMode('intro')} className="flex-1 py-5 rounded-2xl font-bold text-gray-500 hover:text-white hover:bg-white/5 transition-all border border-transparent hover:border-white/10">
                            BEKOR QILISH
                        </button>
                        <button onClick={startExam} className="flex-[2] bg-red-600 text-white py-5 rounded-2xl font-black text-xl hover:bg-red-500 transition-all shadow-[0_0_30px_rgba(220,38,38,0.4)] hover:scale-105 transform duration-300">
                            TUSHUNDIM & BOSHLASH
                        </button>
                    </div>
                </div>
            </div>
        );
    }

    // EXAM INTERFACE
    if (mode === 'exam' || mode === 'practice') {
        const question = questions[currentQIndex];
        if (!question) return <div className="min-h-screen bg-black flex items-center justify-center text-white">Loading question...</div>;

        return (
            <div className="h-screen bg-black text-gray-200 flex flex-col overflow-hidden select-none font-sans">
                {/* Top Bar */}
                <div className="bg-void-panel border-b border-white/10 h-20 flex justify-between items-center px-8 z-30 shadow-lg">
                    <div className="flex items-center gap-6">
                        <div className="font-black text-2xl text-white tracking-tighter">SAT<span className="text-cyber">.UZ</span></div>
                        <div className="h-8 w-px bg-white/10"></div>
                        <div className="flex flex-col">
                            <span className="text-xs font-bold uppercase tracking-widest text-gray-500">Section 1</span>
                            <span className="text-white font-bold">Reading & Writing</span>
                        </div>
                    </div>
                    
                    <div className="flex items-center gap-6">
                        <button className="text-gray-400 hover:text-white flex items-center gap-2 text-sm font-bold transition-colors">
                            <Calculator size={18} /> Calculator
                        </button>
                        <button className="text-gray-400 hover:text-white flex items-center gap-2 text-sm font-bold transition-colors">
                            <BookOpen size={18} /> Reference
                        </button>
                        <div className={`font-mono text-2xl font-black text-white bg-black px-6 py-2 rounded-lg border border-white/10 tabular-nums ${timeLeft < 300 ? 'text-red-500 border-red-500/50 animate-pulse' : ''}`}>
                            {formatTime(timeLeft)}
                        </div>
                        <button onClick={() => setMode('results')} className="bg-white text-black px-6 py-2.5 rounded-lg font-bold text-sm hover:bg-gray-200 transition-colors">
                            Finish Exam
                        </button>
                    </div>
                </div>

                {/* Split Screen Content */}
                <div className="flex-1 flex overflow-hidden relative">
                    {/* Left: Passage */}
                    <div className="w-1/2 border-r border-white/10 p-12 overflow-y-auto custom-scrollbar bg-void-lighter">
                        {question.passage ? (
                            <div className="max-w-3xl mx-auto">
                                <div className="mb-6 text-xs text-cyber font-black uppercase tracking-widest bg-cyber/10 inline-block px-3 py-1 rounded border border-cyber/20">Passage</div>
                                <p className="text-xl leading-loose font-serif text-gray-200">{question.passage}</p>
                            </div>
                        ) : (
                            <div className="flex flex-col items-center justify-center h-full text-gray-700">
                                <div className="p-6 bg-white/5 rounded-full mb-4">
                                    <BookOpen size={48} className="opacity-50" />
                                </div>
                                <p className="font-mono text-sm">NO REFERENCE TEXT FOR THIS QUESTION</p>
                            </div>
                        )}
                    </div>

                    {/* Right: Question */}
                    <div className="w-1/2 p-12 overflow-y-auto custom-scrollbar bg-black relative">
                        <div className="max-w-2xl mx-auto">
                            <div className="flex justify-between items-center mb-8">
                                <div className="bg-white/10 text-white px-4 py-1.5 rounded text-sm font-bold border border-white/10">
                                    Question {currentQIndex + 1} / {questions.length}
                                </div>
                                <button 
                                    onClick={() => setFlags(prev => prev.includes(question.id) ? prev.filter(id => id !== question.id) : [...prev, question.id])}
                                    className={`flex items-center gap-2 text-xs font-bold px-4 py-2 rounded transition-all border ${flags.includes(question.id) ? 'text-red-500 bg-red-500/10 border-red-500/30' : 'text-gray-500 hover:text-white border-transparent hover:bg-white/5'}`}
                                >
                                    <Flag size={16} fill={flags.includes(question.id) ? "currentColor" : "none"} /> MARK FOR REVIEW
                                </button>
                            </div>

                            <p className="text-2xl font-medium text-white mb-10 leading-relaxed">
                                {question.text}
                            </p>

                            <div className="space-y-4">
                                {question.options?.map((opt, idx) => {
                                    const isSelected = answers[question.id] === idx;
                                    return (
                                        <button
                                            key={idx}
                                            onClick={() => handleAnswer(idx)}
                                            className={`w-full text-left p-6 rounded-2xl border-2 transition-all flex items-center gap-6 group relative overflow-hidden ${
                                                isSelected 
                                                ? 'border-cyber bg-cyber/10 text-white shadow-[0_0_30px_rgba(0,240,255,0.1)]' 
                                                : 'border-white/10 text-gray-400 hover:border-white/30 hover:bg-white/5 hover:text-gray-200'
                                            }`}
                                        >
                                            <div className={`w-10 h-10 rounded-full border-2 flex items-center justify-center text-sm font-bold transition-colors flex-shrink-0 ${isSelected ? 'border-cyber bg-cyber text-black' : 'border-gray-600 group-hover:border-white group-hover:text-white'}`}>
                                                {String.fromCharCode(65 + idx)}
                                            </div>
                                            <span className="text-xl leading-snug">{opt}</span>
                                        </button>
                                    )
                                })}
                            </div>
                        </div>
                    </div>
                </div>

                {/* Bottom Nav */}
                <div className="bg-void-panel border-t border-white/10 h-24 flex justify-between items-center px-8 z-30">
                    <div className="flex flex-col">
                        <span className="text-sm font-bold text-white">Azizbek Tolipov</span>
                        <span className="text-xs text-gray-500 font-mono">ID: 8821-X99</span>
                    </div>
                    <div className="flex gap-4">
                        <button 
                            onClick={() => setCurrentQIndex(Math.max(0, currentQIndex - 1))}
                            className="px-8 py-3 bg-white/5 hover:bg-white/10 text-white rounded-xl font-bold disabled:opacity-50 border border-white/10 transition-all"
                            disabled={currentQIndex === 0}
                        >
                            Back
                        </button>
                        <button 
                            onClick={() => setCurrentQIndex(Math.min(questions.length - 1, currentQIndex + 1))}
                            className="px-10 py-3 bg-blue-600 text-white rounded-xl font-bold hover:bg-blue-500 transition-colors shadow-lg flex items-center gap-2"
                        >
                            Next <ChevronRight size={20} />
                        </button>
                    </div>
                </div>
                
                {/* Exit Warning Overlay */}
                {showExitWarning && (
                    <div className="absolute inset-0 bg-red-900/90 backdrop-blur-xl z-50 flex flex-col items-center justify-center p-8 text-center animate-in zoom-in duration-300">
                        <AlertTriangle size={100} className="text-white mb-8 animate-bounce" />
                        <h2 className="text-6xl font-black text-white mb-4">SECURITY ALERT</h2>
                        <p className="text-2xl text-red-200 mb-12 max-w-2xl">
                            Full-screen exit or tab switch detected. This incident has been logged by the AI Proctor.
                        </p>
                        <button 
                            onClick={() => {
                                setShowExitWarning(false);
                                // Try to re-enter fullscreen
                                if (document.documentElement.requestFullscreen) {
                                    document.documentElement.requestFullscreen().catch(()=>{});
                                }
                            }}
                            className="bg-white text-red-900 px-12 py-6 rounded-2xl font-black text-2xl hover:scale-105 transition-transform"
                        >
                            RETURN TO EXAM
                        </button>
                    </div>
                )}
            </div>
        );
    }

    // RESULTS SCREEN
    return (
        <div className="min-h-screen bg-black flex items-center justify-center p-4 relative overflow-hidden">
            <div className="absolute inset-0 grid-bg opacity-20"></div>
            <div className="bg-void-lighter p-16 rounded-[40px] border border-white/10 text-center max-w-3xl w-full relative z-10 shadow-2xl animate-in slide-in-from-bottom">
                <div className="w-32 h-32 bg-green-500/10 rounded-full flex items-center justify-center mx-auto mb-8 border border-green-500/30">
                    <CheckCircle size={64} className="text-green-500" />
                </div>
                <h2 className="text-6xl font-black text-white mb-2">SCORE REPORT</h2>
                <p className="text-gray-400 text-xl mb-12">Exam Session #8821 Complete</p>
                
                <div className="grid grid-cols-2 gap-8 mb-12">
                    <div className="bg-black border border-white/10 p-8 rounded-3xl">
                        <div className="text-gray-500 text-sm font-bold uppercase mb-2">Total Score</div>
                        <div className="text-6xl font-black text-white">{Math.round((score / questions.length) * 1600)}</div>
                    </div>
                    <div className="bg-black border border-white/10 p-8 rounded-3xl">
                        <div className="text-gray-500 text-sm font-bold uppercase mb-2">Accuracy</div>
                        <div className="text-6xl font-black text-cyber">{Math.round((score / questions.length) * 100)}%</div>
                    </div>
                </div>

                <button onClick={() => setMode('intro')} className="bg-white/10 text-white px-12 py-4 rounded-2xl font-bold hover:bg-white/20 hover:scale-105 transition-all border border-white/10">
                    Return to Dashboard
                </button>
            </div>
        </div>
    );
};

export default ExamSimulator;
