import React, { useState, useEffect } from 'react';
import { RefreshCw, Brain, Check, X, Layers, Sparkles, Clock } from 'lucide-react';

interface Flashcard {
    id: number;
    front: string;
    back: string;
    strength: number; // 0-100
    category: string;
    nextReview: string;
}

const INITIAL_CARDS: Flashcard[] = [
    { id: 1, front: "Quadratic Formula", back: "x = (-b ± √(b² - 4ac)) / 2a", strength: 85, category: "Math", nextReview: "2 days" },
    { id: 2, front: "Pythagorean Theorem", back: "a² + b² = c²", strength: 95, category: "Math", nextReview: "5 days" },
    { id: 3, front: "SohCahToa", back: "Sine=Opp/Hyp, Cosine=Adj/Hyp, Tangent=Opp/Adj", strength: 40, category: "Trig", nextReview: "10 mins" },
    { id: 4, front: "Circumference", back: "C = 2πr or C = πd", strength: 60, category: "Geometry", nextReview: "1 day" },
    { id: 5, front: "Slope Formula", back: "m = (y₂ - y₁) / (x₂ - x₁)", strength: 20, category: "Algebra", nextReview: "Now" }
];

const FlashcardSystem: React.FC = () => {
    const [cards, setCards] = useState<Flashcard[]>(INITIAL_CARDS);
    const [currentIndex, setCurrentIndex] = useState(0);
    const [isFlipped, setIsFlipped] = useState(false);
    const [generating, setGenerating] = useState(false);

    const currentCard = cards[currentIndex];

    const handleFlip = () => setIsFlipped(!isFlipped);

    const handleResponse = (know: boolean) => {
        const newCards = [...cards];
        if (know) {
            newCards[currentIndex].strength = Math.min(100, newCards[currentIndex].strength + 20);
        } else {
            newCards[currentIndex].strength = Math.max(0, newCards[currentIndex].strength - 30);
        }
        setCards(newCards);
        setIsFlipped(false);
        setTimeout(() => {
            setCurrentIndex((prev) => (prev + 1) % cards.length);
        }, 300);
    };

    const generateAI = () => {
        setGenerating(true);
        setTimeout(() => {
            setCards(prev => [...prev, {
                id: Date.now(),
                front: "AI Generated Concept " + (prev.length + 1),
                back: "Complex definition generated by Neural Network...",
                strength: 0,
                category: "AI Math",
                nextReview: "Now"
            }]);
            setGenerating(false);
        }, 1500);
    };

    return (
        <div className="min-h-screen bg-black pt-24 px-4 pb-12">
            <div className="max-w-4xl mx-auto h-[80vh] flex flex-col">
                <div className="flex justify-between items-center mb-8">
                    <div>
                        <h1 className="text-3xl font-black text-white flex items-center gap-3">
                            <Layers className="text-cyber" size={32} />
                            NEURAL FLASHCARDS
                        </h1>
                        <p className="text-gray-400 text-sm">Spaced Repetition System (SRS) v9.0</p>
                    </div>
                    <button 
                        onClick={generateAI}
                        disabled={generating}
                        className="bg-white/10 border border-cyber/30 text-white px-6 py-2 rounded-xl hover:bg-cyber/20 transition-all flex items-center gap-2"
                    >
                        {generating ? <RefreshCw className="animate-spin" size={18} /> : <Sparkles size={18} />}
                        {generating ? 'GENERATING...' : 'AI CARD GENERATOR'}
                    </button>
                </div>

                {/* Progress Bar */}
                <div className="w-full bg-gray-800 h-2 rounded-full mb-8 overflow-hidden">
                    <div 
                        className="h-full bg-gradient-to-r from-blue-500 to-cyber transition-all duration-500"
                        style={{ width: `${((currentIndex + 1) / cards.length) * 100}%` }}
                    ></div>
                </div>

                {/* Card Container */}
                <div className="flex-1 flex flex-col items-center justify-center relative perspective-1000">
                    <div 
                        className={`
                            relative w-full max-w-xl aspect-[3/2] cursor-pointer transition-transform duration-700 transform-style-3d
                            ${isFlipped ? 'rotate-y-180' : ''}
                        `}
                        onClick={handleFlip}
                    >
                        {/* Front */}
                        <div className="absolute inset-0 bg-void-lighter border border-white/10 rounded-3xl p-8 flex flex-col items-center justify-center backface-hidden shadow-[0_0_50px_rgba(0,0,0,0.5)] group hover:border-cyber/30">
                            <div className="absolute top-6 left-6 flex items-center gap-2">
                                <span className="text-xs font-bold bg-white/5 px-3 py-1 rounded-full text-gray-400 border border-white/5">
                                    {currentCard.category}
                                </span>
                            </div>
                            <div className="absolute top-6 right-6">
                                <div className="flex items-center gap-2 text-xs text-gray-500">
                                    <Clock size={12} /> Review: {currentCard.nextReview}
                                </div>
                            </div>
                            
                            <h2 className="text-3xl md:text-4xl font-black text-white text-center">
                                {currentCard.front}
                            </h2>
                            
                            <div className="absolute bottom-6 text-gray-500 text-sm animate-pulse">
                                Kartani ko'rish uchun bosing
                            </div>
                        </div>

                        {/* Back */}
                        <div className="absolute inset-0 bg-gradient-to-br from-cyber/10 to-blue-900/20 border border-cyber/50 rounded-3xl p-8 flex flex-col items-center justify-center backface-hidden rotate-y-180 shadow-[0_0_50px_rgba(0,240,255,0.1)]">
                             <h2 className="text-2xl md:text-3xl font-medium text-cyber text-center leading-relaxed">
                                {currentCard.back}
                            </h2>
                             <div className="absolute top-6 right-6 text-cyber">
                                <Brain size={24} />
                            </div>
                        </div>
                    </div>

                    {/* Controls */}
                    <div className="mt-12 flex gap-8">
                        <button 
                            onClick={() => handleResponse(false)}
                            className="w-16 h-16 rounded-full bg-red-500/10 border border-red-500/50 text-red-500 flex items-center justify-center hover:bg-red-500 hover:text-white transition-all transform hover:scale-110"
                        >
                            <X size={32} />
                        </button>
                        <button 
                            onClick={handleFlip}
                            className="w-16 h-16 rounded-full bg-white/5 border border-white/20 text-white flex items-center justify-center hover:bg-white/20 transition-all transform hover:scale-110"
                        >
                            <RefreshCw size={24} />
                        </button>
                        <button 
                            onClick={() => handleResponse(true)}
                            className="w-16 h-16 rounded-full bg-green-500/10 border border-green-500/50 text-green-500 flex items-center justify-center hover:bg-green-500 hover:text-white transition-all transform hover:scale-110"
                        >
                            <Check size={32} />
                        </button>
                    </div>
                    
                    <div className="mt-6 flex items-center gap-4 text-xs font-mono text-gray-500">
                        <span>MEMORY STRENGTH:</span>
                        <div className="w-32 h-2 bg-gray-800 rounded-full overflow-hidden">
                             <div 
                                className={`h-full transition-all duration-500 ${currentCard.strength > 80 ? 'bg-green-500' : currentCard.strength > 40 ? 'bg-yellow-500' : 'bg-red-500'}`}
                                style={{ width: `${currentCard.strength}%` }}
                            ></div>
                        </div>
                        <span>{currentCard.strength}%</span>
                    </div>
                </div>
            </div>
            
            <style>{`
                .perspective-1000 { perspective: 1000px; }
                .transform-style-3d { transform-style: preserve-3d; }
                .backface-hidden { backface-visibility: hidden; }
                .rotate-y-180 { transform: rotateY(180deg); }
            `}</style>
        </div>
    );
};

export default FlashcardSystem;